[package]
name = "homework_5"
version = "0.1.0"
authors = ["Jacob Rivera <edjacob25@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
time = "0.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false
